color: null
description: null
fieldLayouts:
  2c05c4cc-4b95-43e8-9467-6647341458b0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-13T11:02:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9a6dba0b-f08b-4808-972b-c05d256a3c3f # Heading
            handle: itemTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98675d42-d44d-462a-8ce5-9ab3436fae8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-13T11:02:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f53721fc-dc3d-4ae1-88b5-f3af79963912 # Rich Text
            handle: itemContent
            includeInCards: false
            instructions: null
            label: Content
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d72ff488-e2c5-42fe-86f6-ac6484c770a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 69ad3290-1caa-41ca-8667-78f31b83cdd1
        userCondition: null
handle: accordionItem
hasTitleField: false
icon: messages
name: 'Question & Answer'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: "{{ itemTitle|striptags }} / {{ itemContent|striptags|split(' ')|slice(0, 10)|join(' ') ~ '...' }}"
titleTranslationKeyFormat: null
titleTranslationMethod: site
