color: null
description: null
fieldLayouts:
  067b7718-8ff0-46b7-8af2-af098d7e3efc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 916eb1ec-b18c-4184-a718-1caff6755b5d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 39d30d0b-28d5-4f77-8302-a426460014ac # Company Name
            handle: null
            includeInCards: true
            instructions: null
            label: 'Company Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c6ab72f-d024-4862-9413-51e5b660502d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: f96c62d2-f6a9-40f8-8a85-0c30354e59be # Address - Address Line 1
            handle: null
            includeInCards: false
            instructions: null
            label: 'Address Line 1'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ae94738-16fe-4926-8fe7-fdc4fb9a1aec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 9c5c3197-a7ec-4513-828b-a7dec4c278ea # Address - Address Line 2
            handle: null
            includeInCards: false
            instructions: null
            label: 'Address Line 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd7f718e-ee6b-4fe8-94e8-0998488959cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 232c396c-f786-4ec9-8fa3-9c36b3a392b6 # Address - Address Line 3
            handle: null
            includeInCards: false
            instructions: null
            label: 'Address Line 3'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e454e458-4257-4076-b925-c7d505e7bbb7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 3f8360fd-a038-48f2-97c7-251dc5e05560 # Address - Town/City
            handle: null
            includeInCards: false
            instructions: null
            label: Town/City
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5a8cd6e-d4e1-4655-91c9-136b0fbfe6cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: b90c49a5-ba40-40da-9960-652d13796403 # Address - County
            handle: null
            includeInCards: false
            instructions: null
            label: County
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74fc65d5-7e23-4bc2-8bc6-a766ae0f4919
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 25cbfe34-61e1-4e6d-97b8-c1c08f098b95 # Address - Postcode
            handle: null
            includeInCards: false
            instructions: null
            label: Postcode
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b976dff3-f165-421b-b7a3-30b128b8ef01
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 903b9664-f543-4226-8f72-68a4adb28992 # Address - Country
            handle: null
            includeInCards: false
            instructions: null
            label: Country
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce81a51b-89b0-48cc-b66c-fe9b4d252e1b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3dd26b59-7edd-4f66-9446-c5c5b297f605
        userCondition: null
handle: address
hasTitleField: false
icon: address-card
name: Address
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
