color: null
description: null
fieldLayouts:
  7afabef5-1b05-4d35-ac5d-0f143d0189ec:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:4a9047cc-d30d-4af0-b60b-1fb707467105'
      - 'layoutElement:d5d3c0a7-ef40-4b95-b25a-4a7747c431a7'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-02T06:35:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: afb67af8-81d2-4fb9-bbbc-d422e80104cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-06T14:25:11+00:00'
            elementCondition: null
            heading: 'Error Page'
            type: craft\fieldlayoutelements\Heading
            uid: a49b4815-9ce2-462c-8623-5b1e38214e20
            userCondition: null
          -
            dateAdded: '2025-06-02T06:35:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9a6dba0b-f08b-4808-972b-c05d256a3c3f # Heading
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a9047cc-d30d-4af0-b60b-1fb707467105
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-02T06:35:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f53721fc-dc3d-4ae1-88b5-f3af79963912 # Rich Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5d3c0a7-ef40-4b95-b25a-4a7747c431a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-02T06:35:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 26c92ef0-b8e6-469c-88ca-2950876d4469 # Action Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d73c033b-6c97-4ab8-b1af-28e62e4d98f7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cf78b617-bec9-4049-9419-19d1df6a553f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-06T15:01:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e965f04b-1033-42b1-afdc-ddb6ae5bb55d # Footer Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c179770-831b-441f-99f5-58c9a04e0376
            userCondition: null
            warning: null
            width: 100
        name: 'Footer Content'
        uid: 6723becd-a60a-4f91-8388-a73196b0b35d
        userCondition: null
handle: error
hasTitleField: true
icon: triangle-exclamation
name: Error
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
