color: null
description: null
fieldLayouts:
  aebfae39-b7c1-42dd-8257-c85f299dc051:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1bdc1eba-5c0c-4d4e-883d-6d9b0c3b3aea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: f1c78530-4861-4775-af22-734d110036e4 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d1a1535-45c7-45f6-ab35-20bc71ea99d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c6b12267-56ba-4046-88a6-fdbed7eef046
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
