color: null
description: null
fieldLayouts:
  d7fb46b4-65a0-46f4-8e08-fe7ea3c23459:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:b06fdc1d-9896-45ff-a8a7-99d2d00b5311'
      - 'layoutElement:37081759-650e-444d-b547-3013cf6fd5bb'
      - 'layoutElement:6eca1e13-e502-4ba1-858c-ec115aaacd0c'
      - 'layoutElement:dc3d8230-634f-4383-b8bd-024ef87622e6'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-13T08:15:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f53721fc-dc3d-4ae1-88b5-f3af79963912 # Rich Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b06fdc1d-9896-45ff-a8a7-99d2d00b5311
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T07:58:54+00:00'
            elementCondition: null
            heading: Testimonials
            type: craft\fieldlayoutelements\Heading
            uid: d5f41b19-03d9-4b0f-a9fd-c4c65f9119af
            userCondition: null
          -
            dateAdded: '2025-07-12T15:18:46+00:00'
            elementCondition: null
            template: _cp/tips/testimonials_globals.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 51a6d021-7ccb-4463-80c0-4393b2239166
            userCondition: null
            width: 100
          -
            dateAdded: '2025-07-13T08:08:07+00:00'
            elementCondition: null
            heading: Colours
            type: craft\fieldlayoutelements\Heading
            uid: 55bc5d80-011b-4253-86ba-7186fc42acbd
            userCondition: null
          -
            dateAdded: '2025-07-13T08:02:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 29de51db-42ca-4f70-9664-79678e123674 # Heading Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37081759-650e-444d-b547-3013cf6fd5bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T08:02:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f887805-eb34-411a-aa55-03e1393ec407 # Text Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6eca1e13-e502-4ba1-858c-ec115aaacd0c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T08:02:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b34836a-b2ff-42aa-b2e8-2fac2ef47579 # Background Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc3d8230-634f-4383-b8bd-024ef87622e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19fd6c1b-2196-47cb-8f4f-cbcb8db9d4af
        userCondition: null
handle: testimonials
hasTitleField: false
icon: thumbs-up
name: Testimonials
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Testimonials
titleTranslationKeyFormat: null
titleTranslationMethod: site
