color: null
description: null
fieldLayouts:
  2c1874c5-83c2-40d9-9a4c-ba0454b4d4a1:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:ea74ca87-3e7b-4809-801c-f3ede2c6be3d'
      - 'layoutElement:8fc1e6c3-d11d-4948-8f92-e18f18496295'
      - 'layoutElement:86a3470f-b752-4cf4-8cae-f30f5a9f1a6b'
      - 'layoutElement:3addf797-4628-4522-9421-fd9d6aaf1474'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-27T20:32:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f53721fc-dc3d-4ae1-88b5-f3af79963912 # Rich Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea74ca87-3e7b-4809-801c-f3ede2c6be3d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-26T14:25:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 26c92ef0-b8e6-469c-88ca-2950876d4469 # Action Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de89f5a7-fc4c-4e9a-8d3d-3c4fbde243a3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T10:07:51+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7ed6a20a-8586-4997-b19d-17e8c1357cd2
            userCondition: null
          -
            dateAdded: '2025-04-02T14:09:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 29de51db-42ca-4f70-9664-79678e123674 # Heading Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86a3470f-b752-4cf4-8cae-f30f5a9f1a6b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-11T20:32:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f887805-eb34-411a-aa55-03e1393ec407 # Text Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fc1e6c3-d11d-4948-8f92-e18f18496295
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T10:07:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b34836a-b2ff-42aa-b2e8-2fac2ef47579 # Background Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3addf797-4628-4522-9421-fd9d6aaf1474
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 579e3c52-8435-493f-8e6b-8286098756f4
        userCondition: null
handle: text
hasTitleField: false
icon: text
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Text
titleTranslationKeyFormat: null
titleTranslationMethod: site
