color: null
description: null
fieldLayouts:
  e8a072ae-125a-4da7-9151-81f3356df91f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-06T15:11:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5b8d2960-7db1-4637-9154-e0044544eeae # Trust Link Logo
            handle: logo
            includeInCards: false
            instructions: null
            label: Logo
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9800927c-ad9a-4e4d-a425-eb1a2a5ebce9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T15:11:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8590551-bf07-4230-85fa-807ecb6371e5 # URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e1c2088-274a-47ca-bea9-3d95514712ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 190e687c-f6d5-494b-b44c-7a299f13fe1f
        userCondition: null
handle: trustLink
hasTitleField: false
icon: up-right-from-square
name: 'Trust Link'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Trust Link'
titleTranslationKeyFormat: null
titleTranslationMethod: site
