color: null
description: null
fieldLayouts:
  73f2b641-c8c6-4d19-8cdb-f05dc168db1e:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:e1a14102-d56d-40fd-a2f3-0c7d8acd8956'
      - 'layoutElement:9d967e12-4208-4f58-8c73-05e2aa6c9951'
      - 'layoutElement:4886e199-e400-4e61-bc80-4cac52eb21a5'
      - 'layoutElement:a098483e-d3ff-4b84-a7b9-43688689c495'
      - 'layoutElement:079f58cc-d051-4741-af50-669a9e8314b8'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-28T10:08:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e42bd3e-2753-4261-a252-993210ccbd6e # Use Global USPs
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1a14102-d56d-40fd-a2f3-0c7d8acd8956
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-28T10:08:19+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 740c8a5a-5edb-49f3-96d9-65ceccee1469
            userCondition: null
          -
            dateAdded: '2025-01-11T20:27:29+00:00'
            dismissible: true
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 3e42bd3e-2753-4261-a252-993210ccbd6e # Use Global USPs
                  layoutElementUid: e1a14102-d56d-40fd-a2f3-0c7d8acd8956
                  uid: 90b94d2e-073e-4732-8cab-8f64e95284aa
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            style: tip
            tip: 'USPs can be edited in Globals > Global Content > USPs.'
            type: craft\fieldlayoutelements\Tip
            uid: 0175166d-bf76-4d84-98fc-240e67aed823
            userCondition: null
          -
            dateAdded: '2025-05-28T10:08:19+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 3e42bd3e-2753-4261-a252-993210ccbd6e # Use Global USPs
                  layoutElementUid: e1a14102-d56d-40fd-a2f3-0c7d8acd8956
                  uid: 149d99ff-bd95-45bc-add0-15e5a7e2c9f7
                  value: false
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f53721fc-dc3d-4ae1-88b5-f3af79963912 # Rich Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d967e12-4208-4f58-8c73-05e2aa6c9951
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-28T10:08:19+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 3e42bd3e-2753-4261-a252-993210ccbd6e # Use Global USPs
                  layoutElementUid: e1a14102-d56d-40fd-a2f3-0c7d8acd8956
                  uid: 6df037b1-1dce-4f4d-9b1a-489c3dfb4e05
                  value: false
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 453eb038-5a16-46c6-85dd-6f13bf991d65 # USPs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4f17e19-dec0-44fd-85a4-56a8c9ec527d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-28T10:08:19+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 24c4871b-6a4f-4989-8408-5c672942305a
            userCondition: null
          -
            dateAdded: '2025-05-28T10:08:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 29de51db-42ca-4f70-9664-79678e123674 # Heading Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4886e199-e400-4e61-bc80-4cac52eb21a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-28T10:08:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f887805-eb34-411a-aa55-03e1393ec407 # Text Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a098483e-d3ff-4b84-a7b9-43688689c495
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-11T20:27:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b34836a-b2ff-42aa-b2e8-2fac2ef47579 # Background Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 079f58cc-d051-4741-af50-669a9e8314b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c4398b5-5389-4767-bec7-a80cb41167bf
        userCondition: null
handle: usps
hasTitleField: false
icon: list
name: USPs
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: USPs
titleTranslationKeyFormat: null
titleTranslationMethod: site
