color: null
description: null
fieldLayouts:
  e226afe1-5cb1-4b86-83f4-b29dc6ac4722:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:03df8b52-2a73-4d4b-8070-fa522452f68e'
      - 'layoutElement:ae216621-80a7-4e5e-9ad7-67fb331f75b8'
      - 'layoutElement:03094cb2-19a1-48e3-b98d-dc1033fec80f'
      - 'layoutElement:8392ae93-0a64-42ff-aa91-2111813c4680'
      - 'layoutElement:607d2d83-e62b-4a57-ae2d-83ae776c8cf3'
      - 'layoutElement:398a10f4-136c-4e61-bbfa-301c8fe65019'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-13T20:34:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f53721fc-dc3d-4ae1-88b5-f3af79963912 # Rich Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03df8b52-2a73-4d4b-8070-fa522452f68e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T20:34:00+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: a66ca5c4-aa45-418e-858a-48711c9d2234
            userCondition: null
          -
            dateAdded: '2025-07-08T19:07:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7153c93-193c-4368-9767-21b563ec2f74 # Video URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65b5bf1a-3018-4dc9-9a61-d994f29af474
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T20:34:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f1c78530-4861-4775-af22-734d110036e4 # Image
            handle: posterImage
            includeInCards: true
            instructions: null
            label: 'Alternative Poster Image'
            providesThumbs: true
            required: false
            tip: "Choose an alternative poster image if you don't like the default option."
            type: craft\fieldlayoutelements\CustomField
            uid: 03094cb2-19a1-48e3-b98d-dc1033fec80f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-16T07:47:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: de3beef7-9e23-467f-8aee-5de40661f7f0 # Boolean (Off)
            handle: playInLightbox
            includeInCards: true
            instructions: null
            label: 'Play in Lightbox'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae216621-80a7-4e5e-9ad7-67fb331f75b8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-16T07:52:41+00:00'
            elementCondition: null
            heading: Colours
            type: craft\fieldlayoutelements\Heading
            uid: ca0d5ac2-f7ec-43d5-a150-bdc47ca7c826
            userCondition: null
          -
            dateAdded: '2025-07-16T07:52:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 29de51db-42ca-4f70-9664-79678e123674 # Heading Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8392ae93-0a64-42ff-aa91-2111813c4680
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-16T07:52:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f887805-eb34-411a-aa55-03e1393ec407 # Text Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 607d2d83-e62b-4a57-ae2d-83ae776c8cf3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-16T07:52:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b34836a-b2ff-42aa-b2e8-2fac2ef47579 # Background Colour
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 398a10f4-136c-4e61-bbfa-301c8fe65019
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3832ac15-d2d6-476f-b7a3-3dd4a2778e4c
        userCondition: null
handle: video
hasTitleField: false
icon: play
name: Video
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
