css: ".ck-content span.font-display {\r\n  font-family: 'DM Serif Display', serif;\r\n  font-size: 1.5rem;\r\n}"
headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Rich Text'
options:
  alignment:
    options:
      - left
      - center
      - right
  fontColor:
    colors:
      -
        color: '#181818'
        label: Black
      -
        color: '#FFFFFF'
        label: White
      -
        color: '#bfebff'
        label: 'Pale Blue'
      -
        color: '#48C0F5'
        label: 'Light Blue'
      -
        color: '#149BD7'
        label: 'Dark Blue'
      -
        color: '#fdba74'
        label: 'Light Orange'
      -
        color: '#F5A623'
        label: 'Brand Orange'
      -
        color: '#ea580c'
        label: 'Dark Orange'
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
  style:
    definitions:
      -
        classes:
          - font-sans
        element: span
        name: 'Body Font'
      -
        classes:
          - font-display
        element: span
        name: 'Heading Font'
toolbar:
  - heading
  - style
  - createEntry
  - '|'
  - bold
  - italic
  - fontColor
  - alignment
  - '|'
  - bulletedList
  - numberedList
  - link
  - blockQuote
  - insertTable
  - '|'
  - undo
  - redo
  - '|'
  - sourceEditing
