defaultPlacement: end
fieldLayouts:
  6e523b34-2a67-4643-8114-2a73467ff0dd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-13T10:13:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: ba4d8b06-ba07-434f-b44e-029f26754ac7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T10:13:18+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: b6bc75c2-8474-4061-a258-24a92c33aa61
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2025-07-13T10:13:18+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 1fc4c7d9-dd54-43bd-a858-73e2a4dcf9c5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-13T10:15:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: de3beef7-9e23-467f-8aee-5de40661f7f0 # Boolean (Off)
            handle: useGlobalTelephone
            includeInCards: false
            instructions: 'When enabled, the Telephone number in Globals > Company Info will be used.'
            label: 'Use Global Telephone'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87a28457-eba6-4a42-ae2b-61af9186923a
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: ac003bfa-4560-4c81-9364-e69c1a7e2936
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-07-13T10:13:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 9e4f39dc-974d-45ee-8407-82e19b876032
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-07-13T10:13:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 40cc24e4-a0f0-4276-b9c0-24ef73530ce5
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2025-07-13T10:13:18+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 55f03652-cb63-440e-99a3-b8203e062544
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: c05b53c7-1ffd-4eca-b13b-22374875e6e1
        userCondition: null
handle: actionButtons
instructions: ''
maxNodes: null
name: Actions
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  c5d93292-99d1-44d9-889c-396699fe2e22: # $SYSTEM_NAME
    enabled: true
sortOrder: 5
structure:
  maxLevels: null
  uid: 23afab62-cc1d-4a76-9546-ee49a202a8ea
