altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0fc8477b-8b61-4ea6-8c77-3b108586e97e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9766f423-c6a5-4456-a064-6f3968914166
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d3278c8-b6e8-454a-af20-1ad85d669b01
        userCondition: null
fs: brandAssets
handle: brandAssets
name: 'Brand Assets'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
