altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e050fe83-81b4-4d29-b3c2-b3f7010044e1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6e9fc799-0dd1-4575-ab64-17c3f357b9ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d8eae75-e51f-477a-a927-19d8649bb28f
        userCondition: null
fs: documents
handle: documents
name: Documents
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
