altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1b60fce2-e3f1-494b-ba02-ce86b07034a5:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:238962d5-489f-4e63-9771-e08320155db4'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-07T23:31:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 68eb986f-89fc-47c6-8a87-1253682f7a10
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-07-07T23:32:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: true
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 238962d5-489f-4e63-9771-e08320155db4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df65b909-b542-4e65-861a-4d3b70316b7c
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
