columnSuffix: null
handle: anchorID
instructions: 'Copy this Anchor ID to create In-Page links from other content blocks.'
name: 'Anchor ID'
searchable: false
translationKeyFormat: null
translationMethod: none
type: johnhenry\matrixblockanchor\fields\MatrixBlockAnchorField
