columnSuffix: null
handle: articleBody
instructions: null
name: 'Article Body'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: dfacfb5c-a3b6-4062-9bde-d50b59ecf855 # Rich Text
  createButtonLabel: null
  defaultTransform: null
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - d33e93ca-6f75-431e-98c6-bfbc3764fa2b # Accordion
    -
      __assoc__:
        -
          - uid
          - 861f3771-22e0-495a-bb03-88fa4e34c0c4 # Multi-Column Text
  expandEntryButtons: false
  fullGraphqlData: false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
