columnSuffix: null
handle: backgroundColour
instructions: null
name: 'Background Colour'
searchable: false
settings:
  default: null
  palette: 'Background Colours'
  setRandom: false
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
