columnSuffix: null
handle: booleanOn
instructions: null
name: 'Boolean (On)'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
