columnSuffix: null
handle: codeSingleLine
instructions: null
name: 'Code (Single Line)'
searchable: false
settings:
  availableLanguages:
    - css
    - graphql
    - html
    - javascript
    - json
    - markdown
    - mysql
    - php
    - shell
    - twig
    - typescript
    - yaml
  codeFolding: false
  defaultValue: ''
  fontSize: 14
  language: html
  lineNumbers: false
  monacoEditorOptions: ''
  placeholder: ''
  showLanguageDropdown: false
  singleLineEditor: true
  theme: vs
translationKeyFormat: null
translationMethod: none
type: nystudio107\codefield\fields\Code
