columnSuffix: null
handle: showWebsiteCredit
instructions: null
name: 'Show Website Credit'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
