columnSuffix: null
handle: showGlobalContactForm
instructions: null
name: 'Show Global Contact Form'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
