columnSuffix: null
handle: showGlobalCallToAction
instructions: null
name: 'Show Global Call to Action'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
