columnSuffix: null
handle: showTrustLinks
instructions: null
name: 'Show Trust Links'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
