columnSuffix: null
handle: showSocialNetworks
instructions: null
name: 'Show Social Networks'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
