columnSuffix: null
handle: starRating
instructions: null
name: 'Star Rating'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - ⭐️
        -
          - value
          - '1'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - ⭐️⭐️
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - ⭐️⭐️⭐️
        -
          - value
          - '3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - ⭐️⭐️⭐️⭐️
        -
          - value
          - '4'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - ⭐️⭐️⭐️⭐️⭐️
        -
          - value
          - '5'
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
