columnSuffix: gitzoxjn
handle: theUrl
instructions: null
name: URL
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
