columnSuffix: null
handle: useGlobalFaq
instructions: null
name: 'Use Global FAQ'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
