defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b8a7e45e-98e1-421d-bd6d-b46b4dc24ae8 # Error
handle: errorPages
maxAuthors: 1
name: 'Error Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c5d93292-99d1-44d9-889c-396699fe2e22: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: errors/_entry
    uriFormat: 'error/{slug}'
type: channel
