defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5802ea95-fb4d-48fa-86be-e7f336711daa # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c5d93292-99d1-44d9-889c-396699fe2e22: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
