defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 401cd387-0f69-499c-ad7a-08252bed27cd # Pages
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c5d93292-99d1-44d9-889c-396699fe2e22: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{% if level == 1 or parent.slug == "_home" %}/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: b5670868-319c-420b-9dea-3f88f752aaac
type: structure
