defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: be2faf4c-5ed3-426d-9194-3a17595cf2c8 # Team
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c5d93292-99d1-44d9-889c-396699fe2e22: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: team/_entry.twig
    uriFormat: 'team/{slug}'
structure:
  maxLevels: 1
  uid: 8924e9db-ed1d-4d3d-8b8b-97f2fb2f7fa6
type: structure
